### ISSUE TITLE
False positive on hash symbol for url provider

### ISSUE THREAD

**Issue by d0n473ll0** [LibProtection/libprotection-dotnet#43] opened 2018-04-26 14:32 UTC
In this case everything is fine:
Format string: {0}/{1}/{2}
Data: Assets
jsFile.js
A#

But in this case getting "Attack detected!":
Format string: {0}/{1}/{2}
Data: Assets
jsFile.js
#A

In the second case you could sanitize input too

**Comment by kochetkov** [comment] 2018-05-08 07:09
Duplicate of #41

**Closed as completed** 2018-08-03 14:32 UTC
Labels: duplicate
